   /* tslint:disable */
   export let _MapasMortalidade: any[] = [
              {
                titulo: 'Óbitos Infantis - RS',
                nome: 'Óbitos Infantis - RS ',
                link: 'https://fusiontables.google.com/embedviz?q=select+col26+from+1ZAxGejRZuKEiVSf5McmWMdPtlqceQmNGIviUHDHb&viz=MAP&h=false&lat=-30.32011472088797&lng=-53.375916859375025&t=1&z=6&l=col26&y=14&tmplt=15&hml=KML',
                Ltitulo:['0,0 -  27.429',' 27.430 - 54.857','54.858 - 82.287','82.288 -  109.714',' 109.715 - 137.143', '137.144 - 192.0', '192.1 - 193.0'],
                leg: [
                      'leg14 ',
                      'leg15',
                      'leg16',
                      'leg17',
                      'leg18',
                      'leg19',
                      'leg20',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco', // 7
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco', 
                      'branco',
                    ],

              },
              {
                titulo:'Óbitos Infantis - Indígena',
                nome:'Óbitos Infantis - Indígena',
                link:'https://fusiontables.google.com/embedviz?q=select+col26+from+1ZAxGejRZuKEiVSf5McmWMdPtlqceQmNGIviUHDHb&viz=MAP&h=false&lat=-29.901462995701408&lng=-53.211121937500025&t=1&z=6&l=col26&y=3&tmplt=4&hml=KML',
                Ltitulo:['0 - 0,9','1 - 1,9','2 - 3','',''],
                leg: [
                      'leg21 ',
                      'leg22',
                      'leg23',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco', //3
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco', 
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco'
                    ],
              },        
              
              {
                titulo:'Óbitos Infantis - Pop. Preta',
                nome:'Taxa de Óbitos Infantis - Pop. Preta',
                link:'https://fusiontables.google.com/embedviz?q=select+col26+from+1ZAxGejRZuKEiVSf5McmWMdPtlqceQmNGIviUHDHb&viz=MAP&h=false&lat=-29.663082158777538&lng=-52.892518421875025&t=1&z=6&l=col26&y=5&tmplt=6&hml=KML',
                Ltitulo:['0,0 - 4,4','4,5 - 8,8','8,9 - 13,2','13,3 - 17,6','17,7- 21,0'],
                leg: ['leg24 ',
                      'leg25',
                      'leg26',
                      'leg27',
                      'leg28',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',//5
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco', 
                      'branco',
                      'branco'
                    ],
              },
              {
                titulo:'Óbitos Infantis - Pop. Branca',
                nome:'Óbitos Infantis - Pop. Branca',
                link:'https://fusiontables.google.com/embedviz?q=select+col26+from+1ZAxGejRZuKEiVSf5McmWMdPtlqceQmNGIviUHDHb&viz=MAP&h=false&lat=-29.117461214902278&lng=-53.782411000000025&t=1&z=6&l=col26&y=8&tmplt=9&hml=KML',
                Ltitulo:['0,0 - 20.857','20.858 - 41.714','41.715 - 62.571','62.572 - 83.429','83.430 - 104.286', '104.287 - 125.143','125.144 - 146.0' ],
                leg: [
                  'leg14 ',
                  'leg15',
                  'leg16',
                  'leg17',
                  'leg18',
                  'leg19',
                  'leg20',
                  'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco', // 7
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco',
                      'branco', 
                      'branco', 
                ]
              },
              {
                titulo:'Óbitos Infantis Pop. Parda',
                nome:'Taxa de Óbitos Infantis Pop. Parda',
                link:'https://fusiontables.google.com/embedviz?q=select+col26+from+1ZAxGejRZuKEiVSf5McmWMdPtlqceQmNGIviUHDHb&viz=MAP&h=false&lat=-29.9776248272372&lng=-52.37616100000001&t=1&z=6&l=col26&y=6&tmplt=7&hml=KML',
                Ltitulo:['0,0 - 3,9','4,0 - 8,0','8,1 - 12,0','12,1 - 16,0'],
                leg: [
                  'leg24 ',
                  'leg25',
                  'leg26',
                  'leg27', 
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',//4
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco', 
                  'branco',
                  'branco'
              ],
              },
             
              {
                titulo:'Óbitos Infantis - Infantis Ignorados',
                nome:'Óbitos Infantis - Infantis Ignorados',
                link:'https://fusiontables.google.com/embedviz?q=select+col26+from+1ZAxGejRZuKEiVSf5McmWMdPtlqceQmNGIviUHDHb&viz=MAP&h=false&lat=-29.117461214902278&lng=-53.782411000000025&t=1&z=6&l=col26&y=7&tmplt=8&hml=KML', 
                Ltitulo:['0,0 - 4,0','4,1 - 8,0','8,1 - 12,0','',''],
                leg: [
                  'leg24 ',
                  'leg26',
                  'leg28',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco', 
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco'
                ],
              },

              {
                titulo:'Doenças Feco-Oral - Óbitos por Residência',
                nome:'Doenças Feco-Oral - Óbitos por Residência',
                link:'https://fusiontables.google.com/embedviz?q=select+col26+from+1ZAxGejRZuKEiVSf5McmWMdPtlqceQmNGIviUHDHb&viz=MAP&h=false&lat=-30.50911877459428&lng=-55.781922718750025&t=1&z=6&l=col26&y=11&tmplt=12&hml=KML',
                Ltitulo:['0,0 - 6,143','6.144 - 12.286','12.287 - 18.429','18.430 -   24.571','  24.572 - 30.714', '30.715 - 36.857', '36.858 - 43.0'],
                leg: [
                  'leg14 ',
                  'leg15',
                  'leg16',
                  'leg17',
                  'leg18',
                  'leg19',
                  'leg20',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',
                  'branco',  
                ],

              },



        
            ]
    

