/* tslint:disable */
export let _MapasSaudeAmbiental: any[] = [
    {
      titulo:'Biomas do Rio Grande do Sul',
      nome:'Biomas',
      link:'https://fusiontables.google.com/embedviz?q=select+col13+from+19qswfScrqONnn5_27CYEMRzLBiZFDSRp0MOjQJ1h&viz=MAP&h=false&lat=-30.165250892256093&lng=-54.455476148294&t=1&z=6&l=col13&y=2&tmplt=3&hml=KML',
      Ltitulo:['0,0 - 4,0','4,1 - 8,0','8,1 - 12,0','','','0,0 - 4,0','4,1 - 8,0','8,1 - 12,0','','','0,0 - 4,0','4,1 - 8,0','8,1 - 12,0','','','0,0 - 4,0','4,1 - 8,0','8,1 - 12,0','','','0,0 - 4,0','4,1 - 8,0','8,1 - 12,0','','','0,0 - 4,0','4,1 - 8,0','8,1 - 12,0','',''],
      leg: [
            'leg1',
            'leg2',
            'leg3',
            'leg4',
            'leg5',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco',
            'branco', 
          ],    },
   
];